version: '3.3'

services:
  api:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
