version: '3.3'

services:
  api:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80

    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: streamlit run frontend.py
    ports:
      - 8080:8080
    environment:
      - STREAMLIT_SERVER_PORT=8080
      - API_URL=http://api
    depends_on:
      - api
